/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Dayana
 */
public class registrovyc extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public registrovyc() {
        initComponents();
        pcliente.setVisible(false);
        pvehiculo.setVisible(false);
        pfactura.setVisible(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnsalir = new Vistas.PanelRound();
        btnsalir = new javax.swing.JButton();
        pcliente = new Vistas.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        pempleado = new Vistas.PanelRound();
        btnempleado1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pvehiculo = new Vistas.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        pfactura = new Vistas.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        panelRound2 = new Vistas.PanelRound();
        btncliente1 = new javax.swing.JButton();
        panelRound3 = new Vistas.PanelRound();
        btnvehiculo = new javax.swing.JButton();
        panelRound4 = new Vistas.PanelRound();
        btnfactura = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtusuario1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtusuario2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtusuario3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtusuario4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtusuario5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtusuario6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtusuario7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Nunito", 1, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(215, 125, 91));
        jLabel5.setText("Registro ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo vistas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 440, 120));

        pnsalir.setBackground(new java.awt.Color(215, 125, 91));
        pnsalir.setForeground(new java.awt.Color(0, 0, 0));
        pnsalir.setRoundBottomLeft(30);
        pnsalir.setRoundBottomRight(30);
        pnsalir.setRoundTopLeft(30);
        pnsalir.setRoundTopRight(30);

        btnsalir.setBackground(new java.awt.Color(215, 125, 91));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono5.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnsalirLayout = new javax.swing.GroupLayout(pnsalir);
        pnsalir.setLayout(pnsalirLayout);
        pnsalirLayout.setHorizontalGroup(
            pnsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(14, 14, 14))
        );
        pnsalirLayout.setVerticalGroup(
            pnsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addContainerGap())
        );

        jPanel1.add(pnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 70, 50));

        pcliente.setBackground(new java.awt.Color(215, 125, 91));
        pcliente.setRoundBottomRight(30);
        pcliente.setRoundTopRight(30);
        pcliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clientes");
        pcliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(pcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 130, 60));

        pempleado.setBackground(new java.awt.Color(215, 125, 91));
        pempleado.setRoundBottomLeft(30);
        pempleado.setRoundBottomRight(30);
        pempleado.setRoundTopLeft(30);
        pempleado.setRoundTopRight(30);
        pempleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnempleado1.setBackground(new java.awt.Color(215, 125, 91));
        btnempleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono1.png"))); // NOI18N
        btnempleado1.setBorder(null);
        pempleado.add(btnempleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registro");
        pempleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel1.add(pempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 60));

        pvehiculo.setBackground(new java.awt.Color(215, 125, 91));
        pvehiculo.setRoundBottomRight(30);
        pvehiculo.setRoundTopRight(30);

        jLabel10.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Vehículos");

        javax.swing.GroupLayout pvehiculoLayout = new javax.swing.GroupLayout(pvehiculo);
        pvehiculo.setLayout(pvehiculoLayout);
        pvehiculoLayout.setHorizontalGroup(
            pvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pvehiculoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(22, 22, 22))
        );
        pvehiculoLayout.setVerticalGroup(
            pvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pvehiculoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 130, 60));

        pfactura.setBackground(new java.awt.Color(215, 125, 91));
        pfactura.setRoundBottomRight(30);
        pfactura.setRoundTopRight(30);

        jLabel11.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Facturas");

        javax.swing.GroupLayout pfacturaLayout = new javax.swing.GroupLayout(pfactura);
        pfactura.setLayout(pfacturaLayout);
        pfacturaLayout.setHorizontalGroup(
            pfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfacturaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pfacturaLayout.setVerticalGroup(
            pfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfacturaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(pfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 130, 60));

        panelRound2.setBackground(new java.awt.Color(215, 125, 91));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        btncliente1.setBackground(new java.awt.Color(215, 125, 91));
        btncliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono2.png"))); // NOI18N
        btncliente1.setBorder(null);
        btncliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncliente1MouseExited(evt);
            }
        });
        btncliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btncliente1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btncliente1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        panelRound3.setBackground(new java.awt.Color(215, 125, 91));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        btnvehiculo.setBackground(new java.awt.Color(215, 125, 91));
        btnvehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono3.png"))); // NOI18N
        btnvehiculo.setBorder(null);
        btnvehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnvehiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnvehiculoMouseExited(evt);
            }
        });
        btnvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnvehiculo)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnvehiculo)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        panelRound4.setBackground(new java.awt.Color(215, 125, 91));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);

        btnfactura.setBackground(new java.awt.Color(215, 125, 91));
        btnfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono4.png"))); // NOI18N
        btnfactura.setBorder(null);
        btnfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnfacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnfacturaMouseExited(evt);
            }
        });
        btnfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnfactura)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(btnfactura)
                .addContainerGap())
        );

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 340, 40));

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(215, 125, 91));
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(215, 125, 91));
        jButton1.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 200, 40));

        jLabel6.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(215, 125, 91));
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(215, 125, 91));
        jLabel9.setText("Apellido");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        txtusuario1.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario1.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario1.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 340, 40));

        jLabel12.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(215, 125, 91));
        jLabel12.setText("Correo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        txtusuario2.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario2.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario2.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 340, 40));

        jLabel13.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(215, 125, 91));
        jLabel13.setText("Número de télefono");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        txtusuario3.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario3.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario3.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 340, 40));

        jLabel14.setFont(new java.awt.Font("Nunito", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(215, 125, 91));
        jLabel14.setText("Vehículo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(215, 125, 91));
        jLabel15.setText("Placa");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        txtusuario4.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario4.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario4.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 340, 40));

        jLabel16.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(215, 125, 91));
        jLabel16.setText("Marca");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        txtusuario5.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario5.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario5.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 340, 40));

        jLabel17.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(215, 125, 91));
        jLabel17.setText("Modelo");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, -1, -1));

        txtusuario6.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario6.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario6.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 340, 40));

        jLabel18.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(215, 125, 91));
        jLabel18.setText("Color");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, -1, -1));

        txtusuario7.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario7.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txtusuario7.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 217, 204), 2));
        txtusuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehiculoActionPerformed
        vehiculosem vehiculoFrame = new vehiculosem(); 
        vehiculoFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvehiculoActionPerformed

    private void btnfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaActionPerformed
        facturasem facturaFrame = new facturasem(); 
        facturaFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnfacturaActionPerformed

    private void btncliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncliente1ActionPerformed
        clientesem clienteFrame = new clientesem(); 
        clienteFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncliente1ActionPerformed

    private void btncliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncliente1MouseEntered
         pcliente.setVisible(true); 
    }//GEN-LAST:event_btncliente1MouseEntered

    private void btncliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncliente1MouseExited
        pcliente.setVisible(false); 
    }//GEN-LAST:event_btncliente1MouseExited

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        Login loginFrame = new Login(); 
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnvehiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvehiculoMouseEntered
        pvehiculo.setVisible(true); 
    }//GEN-LAST:event_btnvehiculoMouseEntered

    private void btnvehiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvehiculoMouseExited
        pvehiculo.setVisible(false); 
    }//GEN-LAST:event_btnvehiculoMouseExited

    private void btnfacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaMouseEntered
        pfactura.setVisible(true);
    }//GEN-LAST:event_btnfacturaMouseEntered

    private void btnfacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaMouseExited
        pfactura.setVisible(false);
    }//GEN-LAST:event_btnfacturaMouseExited

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario1ActionPerformed

    private void txtusuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario2ActionPerformed

    private void txtusuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario3ActionPerformed

    private void txtusuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario4ActionPerformed

    private void txtusuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario5ActionPerformed

    private void txtusuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario6ActionPerformed

    private void txtusuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrovyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrovyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrovyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrovyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrovyc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncliente1;
    private javax.swing.JButton btnempleado1;
    private javax.swing.JButton btnfactura;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnvehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private Vistas.PanelRound panelRound2;
    private Vistas.PanelRound panelRound3;
    private Vistas.PanelRound panelRound4;
    private Vistas.PanelRound pcliente;
    private Vistas.PanelRound pempleado;
    private Vistas.PanelRound pfactura;
    private Vistas.PanelRound pnsalir;
    private Vistas.PanelRound pvehiculo;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JTextField txtusuario1;
    private javax.swing.JTextField txtusuario2;
    private javax.swing.JTextField txtusuario3;
    private javax.swing.JTextField txtusuario4;
    private javax.swing.JTextField txtusuario5;
    private javax.swing.JTextField txtusuario6;
    private javax.swing.JTextField txtusuario7;
    // End of variables declaration//GEN-END:variables
}
